# main text of home
name: 
  English: Zhe Cai
  中文: 蔡喆
bio: 
  English: A man who is chasing dreams
  中文: 不畏浮云遮望眼

# twitter summary info
description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets/files/Zhe_Cai_Resume_2020.pdf

url: https://czahie.github.io/
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: czahie # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# instagram: myinstagram
# pinterest: mypinterest
linkedin: czahie
# youtube: myyoutube
# spotify: myspotify
github: czahie
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: czahie1996@gmail.com

authors:
  # johndoe:
  #   name: John Doe
  #   bio: A Man who travels the world eating noodles
  #   external-image: false
  #   picture: assets/images/profile.jpg
  #   twitter: johndoe
  joe:
    name: Zhe Cai
    bio: A man who is chasing dreams
    external-image: false
    picture: assets/images/profile.jpg
    # twitter: jamesfoster
    

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# multi-language support
lang:
  English:
    home: "Home"
    blog: "Blog"
    projects: "Projects"
    about: "About"
    resume: "Résumé"
  中文:
    home:  "首页"
    blog: "博客"
    projects: "项目"
    about: "关于"
    resume: "简历"

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
  ]
